# Default values for quarks-job.
image:
  repository: quarks-job
  org: cfcontainerization
  tag: v0.4.1-120.g604925f0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

rbacEnable: true

serviceAccount:
  quarksJobServiceAccount:
    create: true
    name:

provider: ""
